import argparse
from helpers import print_welcome, get_random_movie_title, download_ai_img, open_img, mask_string, guess_string
from MovieCharadesGUI import MovieCharadesGUI

"""
CS50P Movie Charades GUI or CLI

An interactive game where the user is presented with an AI-generated image from the DALL·E 2 API.
The image is based on a randomly selected movie title from the top 1000 rated movies on MoviesMiniDatabase retrieved through RapidAPI.
The user's task is to guess the movie title associated with the image.

Author: Nedko Dimitrov
Version: 2.0
"""

def main():
    """
    The main function parses command-line arguments to decide which mode to run the game in.
    If the "cli" argument is passed, the game runs in CLI mode, otherwise, it runs in GUI mode.
    """
    parser = argparse.ArgumentParser(description="Play Movie Charades game.")
    parser.add_argument("--cli", action="store_true", help="Run the game in CLI mode")

    args = parser.parse_args()

    if args.cli:
        play_game_cli()
    else:
        # Initialize the game in GUI mode with 3 lives and 3 attempts
        movie_charades_game = MovieCharadesGUI(lives=3, attempts=3)
        movie_charades_game.play_game()


def play_game_cli():
    """
    Play the Movie Charades game in the Command Line Interface (CLI) mode.

    The user is presented with an image generated by the DALL·E 2 API based on a randomly selected movie title.
    The user is prompted to guess the movie title associated with the image. The game continues until the user runs out of lives.
    """
    score = 0
    lives = 3
    attempts = 3
    IMAGE_FILE_NAME = "image.png"

    # Print a welcome message for the user
    print_welcome()

    while lives:
        print(f"score: {score}\tattempts:{attempts}\tlives: {lives}")
        print("Please wait for the AI-generated image to load before guessing the movie title used as the prompt...")
        # Get a random movie title and an AI-generated image based on that title
        movie_title: str = get_random_movie_title()
        download_ai_img(movie_title, IMAGE_FILE_NAME)
        # Open the image for the user to view
        open_img(IMAGE_FILE_NAME)
        # Mask the movie title with underscores to show the user how many letters are present
        print(mask_string(movie_title))

        # Prompt the user to guess the movie title and update the score and lives accordingly
        if guess_string(movie_title, attempts):
            score += 1
            print("Correct!")
        else:
            lives -= 1
            print(f"The movie title was: '{movie_title}'")

    print("Game Over!")


if __name__ == "__main__":
    main()
